alinux: mm, memcg: optimize division operation with memcg counters
Specifically, replace `val / 1000000` with `val >> 20` to do the
optimization.

This also fixes the possible compiling error when building with
ARCH=i386, which reports undefined reference to `__udivdi3`.

Fixes: 40969475355a ("alinux: mm, memcg: record latency of memcg wmark reclaim")
Signed-off-by: Xu Yu <xuyu@linux.alibaba.com>
Reviewed-by: Yang Shi <yang.shi@linux.alibaba.com>